# Generated by Django 5.0.6 on 2025-03-03 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('état', models.CharField(choices=[('Fonctionnel', 'Fonctionnel'), ('En panne', 'En panne'), ('En maintenance', 'En maintenance')], max_length=50)),
                ('date_achat', models.DateField()),
                ('marque', models.CharField(max_length=100)),
                ('modèle', models.CharField(max_length=100)),
                ('numéro_série', models.CharField(max_length=100)),
                ('maintenance_plannée', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='role',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='téléphone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rôle', models.CharField(choices=[('Admin', 'Admin')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_signalement', models.DateTimeField(auto_now_add=True)),
                ('état_incident', models.CharField(choices=[('Non résolu', 'Non résolu'), ('Résolu', 'Résolu')], default='Non résolu', max_length=50)),
                ('résolu', models.BooleanField(default=False)),
                ('équipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='equipments.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prénom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('téléphone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_maintenance', models.CharField(choices=[('Préventive', 'Préventive'), ('Corrective', 'Corrective')], max_length=50)),
                ('date_maintenance', models.DateTimeField()),
                ('commentaire', models.TextField()),
                ('équipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='equipments.equipement')),
                ('technicien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances', to='equipments.technicien')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='technicien_assigné',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements', to='equipments.technicien'),
        ),
    ]
