# Generated by Django 5.0.6 on 2025-03-03 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_equipement_remove_utilisateur_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
