# Generated by Django 5.0.6 on 2025-03-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_notification_lu_alter_notification_type_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='date_achat',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='maintenance_plannée',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='modèle',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='numéro_série',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='technicien_assigné',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='état',
        ),
        migrations.AddField(
            model_name='equipement',
            name='etat',
            field=models.CharField(choices=[('fonctionnel', 'Fonctionnel'), ('panne', 'En panne'), ('maintenance', 'En maintenance')], default='fonctionnel', max_length=50),
        ),
    ]
