# Generated by Django 5.0.6 on 2025-03-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_remove_equipement_date_achat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date_maintenance',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
